<a href="https://colab.research.google.com/github/vinajuliet/python_for_data_scients/blob/main/Latihan_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## soal 1


In [ ]:
import numpy as np

#numpy 1d
arr_1d = np.array([10, 20, 30, 40])
print("Numpy 1d:\n",arr_1d)

print()

#numpy 2d
arr_2d = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print("Numpy 2d:\n",arr_2d)

print()

#numpy 3d
arr_3d = np.array([[[10, 20], [30, 40]], [[50, 60], [70, 80]], [[90, 100], [110, 120]]]) # terdiri dari 3 blok (panjang,lebar,tinggi)
print("Numpy 3d:\n",arr_3d)



Numpy 1d:
 [10 20 30 40]

Numpy 2d:
 [[10 20 30 40]
 [50 60 70 80]]

Numpy 3d:
 [[[ 10  20]
  [ 30  40]]

 [[ 50  60]
  [ 70  80]]

 [[ 90 100]
  [110 120]]]


In [ ]:
#numpy join

import numpy as np

arr_1 = np.array([10, 20])
arr_2 = np.array([30, 40])

arr_joined = np.concatenate((arr_1, arr_2))
print("Numpy join 2d:\n",arr_joined)


# Membuat dua array 3D
arr_3d_1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr_3d_2 = np.array([[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]])

# Menggabungkan dua array 3D menggunakan np.concatenate
arr_3d_joined = np.concatenate((arr_3d_1, arr_3d_2),axis=1)#penggabungan dilakukan sepanjang dimensi baris

print("\nArray 3D setelah join:\n", arr_3d_joined)

Numpy join 2d:
 [10 20 30 40]

Array 3D setelah join:
 [[[ 1  2  3]
  [ 4  5  6]
  [13 14 15]
  [16 17 18]]

 [[ 7  8  9]
  [10 11 12]
  [19 20 21]
  [22 23 24]]]


In [ ]:
#numply split

import numpy as np

arr_split = np.array([10, 20, 30, 40, 50, 60])

split_arr = np.array_split(arr_split, 2)
print(split_arr)


[array([10, 20, 30]), array([40, 50, 60])]


In [ ]:
#numpy operasi matriks
import numpy as np

A = np.array([[10, 20], [30, 40]])
B = np.array([[5, 10], [15, 20]])

C = A - B
print(C)
D = A * B
print(D)


[[ 5 10]
 [15 20]]
[[ 50 200]
 [450 800]]


## soal 2


In [ ]:
#Buatlah numpy array dengan matrik ukuran 3x4 dan range array 10-30

import numpy as np

arr = np.arange(10, 30).reshape(4,5)
print(arr)


#Kemudian lakukan flatten
arr_flatten = arr.flatten()
print(arr_flatten)

#cari nilai statistik (mean, median, dsb)
mean_val = np.mean(arr)
median_val = np.median(arr)
var_val = np.var(arr)
sum_val = np.sum(arr)

print(f"Mean: {mean_val}")
print(f"Median: {median_val}")
print(f"Variance: {var_val}")
print(f"Sum: {sum_val}")




[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Mean: 19.5
Median: 19.5
Variance: 33.25
Sum: 390
